# Embedding Python-based AI Agents into Java Applications version 1.0.
#
# Copyright (c)  2024,  Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
kind: Service
apiVersion: v1
metadata:
  name: langgraph
  labels:
    app: langgraph
spec:
  type: ClusterIP
  selector:
    app: langgraph
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: langgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph
  template:
    metadata:
      labels:
        app: langgraph
        version: v1
    spec:
      containers:
      - name: langgraph
        image: langgraph
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
